spring.application.name=medTrack


spring.datasource.url=jdbc:postgresql://localhost:5432/fhir
spring.datasource.username=fhiruser
spring.datasource.password=fhirpass

spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


spring.data.elasticsearch.repositories.enabled=false
